# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

steps:
- script: 
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Subscription'
        azureResourceManagerConnection: 'Free Trial(e5d852a2-8798-447e-93f1-d012152d08fd)'
        subscriptionId: 'e5d852a2-8798-447e-93f1-d012152d08fd'
        location: 'Central US'
        templateLocation: 'URL of the file'
        csmFileLink: 'Blob-Storage/templateBlob.json'
        csmParametersFileLink: 'Blob-Storage/parametersBlob.json'
        deploymentMode: 'Incremental'